---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: vote-ci
spec:
  pipelineRef:
    name: instavote-ci  # pipeline (template) that this refers to
  podTemplate:
    securityContext:
      fsGroup: 1000  # This ensures files are writable by non-root users
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce  # whether this is available in multiple nodes or just one node
        resources:
          requests:
            storage: 1Gi
  - name: dockerconfig
    secret:
      secretName: dockerhub-creds
  params:
  - name: repoUrl
    value: https://github.com/joaquimcampos/LFD254-example-voting-app.git
  - name: revision
    value: main  # git branch
  - name: sparseCheckoutDirectories
    value: /vote/
  - name: imageUrl
    value: jcampos15/vote
  - name: pathToContext
    value: vote
